#!/bin/bash -l
#SBATCH -A bdshe01
#SBATCH -p gpu
# This works for 32 >= N >= 1 on Bede


# Use all 1 GPUs on a node
#SBATCH --gres=gpu:1



echo $SLURM_JOB_NUM_NODES ' SLURM_JOB_NUM_NODES'
echo $SLURM_NTASKS ' SLURM_NTASKS'
echo $SLURM_CPUS_ON_NODE ' SLURM_CPUS_ON_NODE'


date_start=`date +%s`

hostname
module load OpenMPI/3.1.4-gcccuda-2019b
export MPI_HOME=/opt/software/eb/software/OpenMPI/3.1.4-gcccuda-2019b
export CUDA_INSTALL_PATH=/opt/software/eb/software/CUDA/10.1.243-GCC-8.3.0
which mpirun
which bede-mpirun
# $ROW x $COL should equal the value of GPU used
GPUS=$((4*$SLURM_JOB_NUM_NODES))
ROW=2
COL=4
SIZE=10000
echo "build CUDA Aware MPI"
make all

# 
#

date_end=`date +%s`
seconds=$((date_end-date_start))
minutes=$((seconds/60))
seconds=$((seconds-60*minutes))
hours=$((minutes/60))
minutes=$((minutes-60*hours))
echo =========================================================   
echo SLURM job: finished   date = `date`   
echo Total run time : $hours Hours $minutes Minutes $seconds Seconds
echo =========================================================   

